name: Coverage

on:
  push:
  pull_request:

jobs:
  coverage:
    name: Coverage for ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu"]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@main
        with:
          python-version: "3.10"
          cache: "pip"
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          components: llvm-tools-preview
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - uses: Swatinem/rust-cache@v1
        with:
          key: coverage-cargo-${{ matrix.os }}
        continue-on-error: true
      - name: Setup virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      - name: Run coverage for RSESS & PyRSESS
        run: |
          source venv/bin/activate
          source <(cargo llvm-cov show-env --export-prefix)
          export CARGO_TARGET_DIR=$CARGO_LLVM_COV_TARGET_DIR
          export CARGO_INCREMENTAL=1
          cargo llvm-cov clean --workspace
          cargo test
          cd pyrsess/
          maturin develop
          pytest tests --cov=pyrsess --cov-report xml
          cp *.xml ../
          cd ../
          cargo llvm-cov --no-run --lcov --output-path coverage.lcov
      - uses: codecov/codecov-action@v3
        with:
          files: coverage.lcov,coverage.xml
          name: ${{ matrix.os }}
